id: P007999
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:14.121551
source_metadata:
  id: bdr:W16079
  title: རཱ་མ་ཎའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    de1edcc3d5d64a86a229f399fcccdfa4:
      image_group_id: I1KG12348
      title: Volume 1 of rA ma Na'i rtogs brjod/
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
