id: P007999
initial_creation_type: ocr
source_metadata:
  id: bdr:W16079
  title: རཱ་མ་ཎའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    209e4b7a696e44f99651958c2a8b7ede:
      image_group_id: I1KG12348
      title: ''
      volume_number: 1
      total_pages: 206
ebook_metadata:
  title: རཱ་མ་ཎའི་རྟོགས་བརྗོད།
  author: ''
  sku: P007999
  cover: cover.jpg
  layers:
  - pagination
